name: Create PR from dev to main

on:
  push:
    branches:
      - dev

jobs:
  create-pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: main
        head: dev
        title: "Merge changes from dev to main"
        body: |
          Automated Pull Request:
          - This PR was automatically created after a push to the dev branch
          - Please review the changes before merging
        labels: |
          automatic merge
          dev to main