name: Auto Create PR to Main

on:
  push:
    branches:
      - dev

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Merge changes from dev to main',
              owner,
              repo,
              head: 'dev',
              base: 'main',
              body: 'Automated pull request created after push to dev branch'
            });
            console.log(result);