name: Auto Create PR to Main

on:
  push:
    branches:
      - dev

# Adiciona permissões específicas para a Action
permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head dev \
            --title "Merge changes from dev to main" \
            --body "Automated pull request created after push to dev branch"